//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACERCA_DE
    {
        public string ID_ACERCA_DE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CODIGO { get; set; }
        public string AUTOR { get; set; }
        public string CORREO_AUTOR { get; set; }
    }
}
